apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-script
  namespace: petclinic
data:
  generate-traffic.sh: |
    #!/bin/bash
    
    echo "Starting traffic generation for Pet Clinic..."
    
    PETCLINIC_URL="http://spring-petclinic-service"
    
    # 다양한 엔드포인트 배열
    endpoints=(
        "/"
        "/owners"
        "/owners/new"
        "/owners/find"
        "/vets"
        "/vets.json"
        "/error"
        "/oups"
    )
    
    while true; do
        # 랜덤 엔드포인트 선택
        endpoint=${endpoints[$RANDOM % ${#endpoints[@]}]}
        
        echo "$(date): Accessing ${PETCLINIC_URL}${endpoint}"
        
        # HTTP 요청 전송
        curl -s -o /dev/null -w "HTTP %{http_code} - %{url_effective}\n" \
            "${PETCLINIC_URL}${endpoint}" || echo "Request failed"
        
        # 1-5초 랜덤 대기
        sleep $((RANDOM % 5 + 1))
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: petclinic
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args: ["/scripts/generate-traffic.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: script-volume
        configMap:
          name: traffic-generator-script
          defaultMode: 0755