apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql

resources:
  - namespace.yaml
  - mysql-configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-exporter.yaml

commonLabels:
  app: mysql
  component: database

images:
  - name: mysql
    newTag: "8.0" 