apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
  labels:
    app: mysql
data:
  my.cnf: |
    [mysqld]
    # 일반 설정
    port = 3306
    bind-address = 0.0.0.0
    
    # 문자셋 설정
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    
    # 성능 튜닝
    max_connections = 200
    innodb_buffer_pool_size = 512M
    innodb_log_file_size = 128M
    
    # 로그 설정
    log-error = /var/log/mysql/error.log
    slow_query_log = 1
    slow_query_log_file = /var/log/mysql/slow.log
    long_query_time = 2
    
    # 바이너리 로그 (복제용)
    log-bin = mysql-bin
    server-id = 1
    
    [client]
    default-character-set = utf8mb4 