apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-es-cluster-app
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/AjouEvent/AjouEvent_Manifest.git
    path: monitoring/elastic-cr/elasticsearch  
    targetRevision: HEAD 
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 