apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-kibana-app
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/AjouEvent/AjouEvent_Manifest.git
    path: monitoring/elastic-cr/kibana
    targetRevision: HEAD 
  destination:
    server: https://kubernetes.default.svc
    namespace: kibana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 