apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-es-cluster
  namespace: elastic
spec:
  version: 8.5.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      cluster.routing.allocation.disk.threshold_enabled: false
      indices.memory.index_buffer_size: 20%
      thread_pool.write.queue_size: 500
      thread_pool.search.queue_size: 1000
      
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g -XX:+UseG1GC"
          resources:
            requests:
              memory: "3Gi"  
              cpu: "1500m"   
            limits:
              memory: "4Gi"  
              cpu: "2"       
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path